# Generated by Django 6.0.4 on 2026-05-05 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_profile_course_profile_end_date_profile_joined_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='plain_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
