# Generated by Django 6.0.4 on 2026-06-03 05:38

import api.certificate_models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_payment_receipt_studentfee_payment_student_fee_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Standard Certificate', max_length=200)),
                ('subtitle', models.CharField(default='Certificate of Completion', max_length=200)),
                ('institute_name', models.CharField(default='Krify Training Institute', max_length=200)),
                ('signatory_name', models.CharField(default='Director', max_length=100)),
                ('signatory_title', models.CharField(default='Institute Director', max_length=100)),
                ('background_color', models.CharField(default='#1e1b4b', max_length=20)),
                ('accent_color', models.CharField(default='#6366f1', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.CharField(default=api.certificate_models.generate_certificate_id, max_length=30, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='active', max_length=20)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('completion_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('download_count', models.IntegerField(default=0)),
                ('auto_generated', models.BooleanField(default=False)),
                ('revoke_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to='api.batch')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='api.course')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_certificates', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.certificatetemplate')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('student', 'course')},
            },
        ),
    ]
