# Generated by Django 6.0.4 on 2026-06-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_achievement_atsanalysis_careerreadiness_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='WhatsApp number with country code (e.g., +919876543210)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='institute_name',
            field=models.CharField(default='Kravia Institute', max_length=200),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='institute_name',
            field=models.CharField(default='Kravia Institute', max_length=200),
        ),
    ]
