# Generated by Django 6.0.4 on 2026-05-19 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_notification'),
        ('live_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesession',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_sessions', to='api.course'),
        ),
    ]
