# Generated by Django 6.0.4 on 2026-05-19 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_sessions', '0002_livesession_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesession',
            name='admin_online',
            field=models.BooleanField(default=False),
        ),
    ]
