# Generated by Django 6.0.4 on 2026-05-19 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_sessions', '0003_livesession_admin_online'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebRTCSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_user', models.CharField(max_length=255)),
                ('to_user', models.CharField(blank=True, max_length=255)),
                ('signal_type', models.CharField(max_length=30)),
                ('payload', models.TextField(default='{}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='live_sessions.livesession')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
