# Generated by Django 6.0.4 on 2026-06-01 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('live_sessions', '0004_webrtcsignal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WebRTCSignal',
        ),
    ]
